### ISSUE TITLE
CLI Mode

### ISSUE THREAD

**Issue by josephlewis42** [alash3al/scraply#1]
It would be really nifty to be able to run this from the CLI as a command and have it write the JSON to stdout so it could be used as part of a larger tool. For example:

```
scraply --execute /my-macro
```

**Comment by alash3al** [comment]
It is a good idea, but what kind of use cases for this feature?

**Comment by josephlewis42** [comment]
I would imagine this being useful when looking to crawl for things other than HTML documents or using in shell scripts. For example, you could use Scraply to build up a JSON object describing your data on an image hosting website, and then pass that to another command that would download all your images. In that case you'd want to run the script as part of a larger process (or manually as a script) and may not want to worry about binding to a port, making sure the server terminates, and securing the endpoint.

This is a really cool tool!

**Comment by alash3al** [comment]
Awesome, but this requires a revamp to make it something like this `scraply cli <macroName>` or `scraply http :8090`

**Comment by alash3al** [comment]
I'll try to think in it out of the box and put it into my todos

**Comment by alash3al** [comment]
@josephlewis42 

I know that it is ~two years since you posted your suggestion, but I wanted to let you know that `scraply` now is just a simple CSS selectors scraper with a very simple `cli` interface.
