### ISSUE TITLE
Support params

### ISSUE THREAD

**Issue by josephlewis42** [alash3al/scraply#2]
Supporting params in macros would help make this tool really useful for fetching dynamic content from sites. For example, a vanilla macro could fetch a list of stocks from a website then a separate one could take a name as a parameter and look up that particular stock by constructing a URL.

I imagine constructing a URL could be done similarly to exec:

```.hcl
urlExec = <<JS
        url = {
            scheme: "https",
            host: "stock-lookup.com",
            params: [{"name":"symbol", "value": scraply.params["stock-symbol"]}]
        }
    JS
```

And be called with URL query params:

```
/stock?stock-symbol=AAPL
```

**Comment by alash3al** [comment]
@josephlewis42 I released a new version with the support for passing the query params as `scraply.params`.

If you want to use a dynamic URL, you can utilize the `fetch()` function with `scraply.params` without specifying a URL in the main hcl url
